# Generated by Django 3.0.4 on 2022-03-11 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page_edits', '0010_howweworktext_body'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PrivacyPolicy',
        ),
    ]
